# Database configuration
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

# Access configuration
management:
  security:
    enabled: true
  context-path: /appinfo

# Security configuration
security:
  user:
    name: admin
    password: admin

# Project info
info:
  app:
    description: Amelco final course workshop
    java:
      source: '@java.version@'
    version: '@version@'
    name: Customer Relationship Management

# Internationalization
mvc:
  locale: pl_PL
  locale-resolver: fixed
messages:
  basename: messages/messages